2022-06-16 09:40:36,300	INFO agent.py:83 -- Parent pid is 51751
2022-06-16 09:40:36,300	INFO agent.py:109 -- Dashboard agent grpc address: 0.0.0.0:62346
2022-06-16 09:40:36,304	INFO utils.py:99 -- Get all modules by type: DashboardAgentModule
2022-06-16 09:40:45,393	INFO utils.py:144 -- Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2022-06-16 09:40:45,393	INFO utils.py:147 -- Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-06-16 09:40:47,237	WARNING tune_head.py:23 -- tune module is not available: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.
2022-06-16 09:40:47,300	INFO utils.py:132 -- Available modules: [<class 'ray.dashboard.modules.event.event_agent.EventAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>, <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>, <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>]
2022-06-16 09:40:47,300	INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.event.event_agent.EventAgent'>
2022-06-16 09:40:47,300	INFO event_agent.py:28 -- Event agent cache buffer size: 10240
2022-06-16 09:40:47,301	INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgent'>
2022-06-16 09:40:47,301	INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>
2022-06-16 09:40:47,301	INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>
2022-06-16 09:40:47,434	INFO agent.py:130 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>
2022-06-16 09:40:47,448	INFO agent.py:134 -- Loaded 5 modules.
2022-06-16 09:40:47,556	INFO http_server_agent.py:64 -- Dashboard agent http address: 0.0.0.0:41355
2022-06-16 09:40:47,556	INFO http_server_agent.py:70 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-06-16_09-40-02_493012_50943/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-06-16_09-40-02_493012_50943/logs')>>
2022-06-16 09:40:47,556	INFO http_server_agent.py:70 -- <ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-06-16_09-40-02_493012_50943/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f73ae8d0b50>>
2022-06-16 09:40:47,556	INFO http_server_agent.py:71 -- Registered 2 routes.
2022-06-16 09:40:48,033	INFO event_agent.py:45 -- Report events to b'10.140.1.24:33598'
2022-06-16 09:40:48,033	INFO event_utils.py:127 -- Monitor events logs modified after 1655341840.825263 on /tmp/ray/session_2022-06-16_09-40-02_493012_50943/logs/events, the source types are ['CORE_WORKER', 'COMMON', 'RAYLET'].
2022-06-16 21:15:51,335	INFO runtime_env_agent.py:370 -- Creating runtime env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}} with timeout 600 seconds.
2022-06-16 21:15:51,336	INFO runtime_env_agent.py:413 -- Successfully created runtime env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}, the context: {"command_prefix": [], "env_vars": {"XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:15:51,438	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}, context: {"command_prefix": [], "env_vars": {"XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:15:51,438	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}, context: {"command_prefix": [], "env_vars": {"XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:20:32,152	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}.
2022-06-16 21:20:32,362	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}.
2022-06-16 21:20:32,363	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}.
2022-06-16 21:20:32,363	INFO runtime_env_agent.py:137 -- Unused runtime env {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}}.
2022-06-16 21:20:32,363	INFO runtime_env_agent.py:240 -- Runtime env {"envVars": {"ALPA_IS_WORKER": "True", "NCCL_USE_MULTISTREAM": "False", "XLA_FLAGS": "--xla_gpu_cuda_data_dir=/mnt/cache/share/platform/dep/cuda11.2-cudnn8.1.1 --xla_gpu_enable_async_all_reduce=false --xla_gpu_enable_async_all_reduce=false --xla_gpu_autotune_level=4", "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.9"}} deleted.
2022-06-16 21:47:21,414	INFO runtime_env_agent.py:370 -- Creating runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} with timeout 600 seconds.
2022-06-16 21:47:21,416	INFO runtime_env_agent.py:413 -- Successfully created runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, the context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:47:21,416	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:47:21,416	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:47:21,416	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 21:50:09,229	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 21:50:09,229	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 21:50:09,230	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 21:50:09,230	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 21:50:09,230	INFO runtime_env_agent.py:137 -- Unused runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 21:50:09,230	INFO runtime_env_agent.py:240 -- Runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} deleted.
2022-06-16 22:21:22,466	INFO runtime_env_agent.py:370 -- Creating runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} with timeout 600 seconds.
2022-06-16 22:21:22,468	INFO runtime_env_agent.py:413 -- Successfully created runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, the context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:21:22,468	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:21:22,468	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:21:22,468	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:21:22,468	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:24:32,135	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:24:32,213	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:24:32,213	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:24:32,213	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:24:32,213	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:24:32,214	INFO runtime_env_agent.py:137 -- Unused runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:24:32,214	INFO runtime_env_agent.py:240 -- Runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} deleted.
2022-06-16 22:32:47,325	INFO runtime_env_agent.py:370 -- Creating runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} with timeout 600 seconds.
2022-06-16 22:32:47,326	INFO runtime_env_agent.py:413 -- Successfully created runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, the context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:32:47,326	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:32:47,326	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:32:47,326	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:32:47,327	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:35:50,654	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:35:50,654	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:35:50,655	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:35:50,655	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:35:50,655	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:35:50,655	INFO runtime_env_agent.py:137 -- Unused runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:35:50,655	INFO runtime_env_agent.py:240 -- Runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} deleted.
2022-06-16 22:45:39,184	ERROR reporter_agent.py:706 -- Error publishing node physical stats.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 442, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1642, in wrapper
    return fun(self, *args, **kwargs)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 445, in wrapper
    return fun(self)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1684, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 775, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 763, in cat
    with _open(fname) as f:
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 727, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/58079/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 700, in _perform_iteration
    stats = self._get_all_stats()
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 421, in _get_all_stats
    "workers": self._get_workers(),
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 349, in _get_workers
    for w in self._workers
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 350, in <listcomp>
    if w.status() != psutil.STATUS_ZOMBIE
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/__init__.py", line 686, in status
    return self._proc.status()
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1642, in wrapper
    return fun(self, *args, **kwargs)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 2176, in status
    letter = self._parse_stat_file()['status']
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1649, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=58079)
2022-06-16 22:52:28,659	INFO runtime_env_agent.py:370 -- Creating runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} with timeout 600 seconds.
2022-06-16 22:52:28,661	INFO runtime_env_agent.py:413 -- Successfully created runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, the context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:52:28,661	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:52:28,661	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:52:28,661	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:52:28,661	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 22:55:37,296	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:55:37,317	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:55:37,317	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:55:37,318	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:55:37,318	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:55:37,318	INFO runtime_env_agent.py:137 -- Unused runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 22:55:37,318	INFO runtime_env_agent.py:240 -- Runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} deleted.
2022-06-16 23:11:18,850	INFO runtime_env_agent.py:370 -- Creating runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} with timeout 600 seconds.
2022-06-16 23:11:18,851	INFO runtime_env_agent.py:413 -- Successfully created runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, the context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 23:11:18,851	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 23:11:18,852	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 23:11:18,852	INFO runtime_env_agent.py:447 -- Runtime env already created successfully. Env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}, context: {"command_prefix": [], "env_vars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0", "PYTHONPATH": ""}, "py_executable": "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/bin/python", "resources_dir": null, "container": {}}
2022-06-16 23:14:31,675	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 23:14:31,676	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 23:14:31,677	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 23:14:31,677	INFO runtime_env_agent.py:514 -- Got request from raylet to decrease reference for runtime env: {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 23:14:31,677	INFO runtime_env_agent.py:137 -- Unused runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}}.
2022-06-16 23:14:31,677	INFO runtime_env_agent.py:240 -- Runtime env {"envVars": {"XLA_FLAGS": "--xla_gpu_autotune_level=0"}} deleted.
2022-06-16 23:22:16,313	ERROR reporter_agent.py:706 -- Error publishing node physical stats.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 442, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1642, in wrapper
    return fun(self, *args, **kwargs)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 445, in wrapper
    return fun(self)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1684, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 775, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 763, in cat
    with _open(fname) as f:
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_common.py", line 727, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/99889/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 700, in _perform_iteration
    stats = self._get_all_stats()
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 421, in _get_all_stats
    "workers": self._get_workers(),
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 349, in _get_workers
    for w in self._workers
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 350, in <listcomp>
    if w.status() != psutil.STATUS_ZOMBIE
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/__init__.py", line 686, in status
    return self._proc.status()
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1642, in wrapper
    return fun(self, *args, **kwargs)
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 2176, in status
    letter = self._parse_stat_file()['status']
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/thirdparty_files/psutil/_pslinux.py", line 1649, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=99889)
